#! /bin/sh

#####################################################
# Name: lists
#
# Helper script the lists filesystem structure
#
# Usage: lists <action> [list] [listitem]
#
# Dependencies: tree
#
# License: GPLv3
#
# Version: 0.1
# Author: asyncial
# Date of Creation: 2018-04-23
######################################################

# Settings
LIST_ROOT=~/lists

# Globals
LIST=""
LIST_ITEM=""

# Functions
init () {
    mkdir -p ${LIST_ROOT}
}

add () {
    mkdir -p "${LIST_ROOT}/${LIST}"
    if [ "${LIST_ITEM}" != "" ]; then
        touch "${LIST_ROOT}/${LIST}/${LIST_ITEM}"
    fi
}

del () {
    if [ "${LIST_ITEM}" = "" ]; then
        rm -rf "${LIST_ROOT:?}/${LIST}"
    else
        rm "${LIST_ROOT}/${LIST}/${LIST_ITEM}"
    fi
}

#rename () {
#
#}

show () {
    if [ "${LIST}" = "" ]; then
        cd "${LIST_ROOT}" || return
        tree --noreport -d
    else
        cd "${LIST_ROOT}/${LIST}" || return
        tree --noreport
    fi
}

finish () {
    mv "${LIST_ROOT}/${LIST}/${LIST_ITEM}" "${LIST_ROOT}/${LIST}/.${LIST_ITEM}"
}

edit () {
    $EDITOR "${LIST_ROOT}/${LIST}/${LIST_ITEM}"
}

show_help () {
    echo "Following actions are available"
    echo "init, add, show, finish, edit, del, show_help"
}

# Main functionality. Evaluates the given arguments.

main () {
    local usage
    usage="lists <action> [list] [listitem]. lists show_help for more."
    local action
    action=${1}
    LIST=${2}
    LIST_ITEM=${3}

    case $action in
        init) init
            ;;
        add) add
            ;;
        del) del
            ;;
        show) show
            ;;
#        rename) rename
#            ;;
        finish) finish
            ;;
        edit) edit
            ;;
        help) show_help
            ;;
        *) show
            echo "$usage"
            ;;
    esac
}
main "$@"
